const express = require('express')
const route = express.Router();

route.use("/auth", require("./auth/auth.route"))
route.use("/task", require("./Task/task"))
route.use("/push", require("./push.route"))
route.use("/google", require("./google.route"))
route.use("/brands", require("./brand.route"))
route.use("/companies", require("./company.route"))
route.use("/task-types", require("./taskType.route"))
route.use("/company-brand-task-types", require("./companyBrandTaskType.route"))
route.use("/company-task-types", require("./companyTaskType.route"))
route.use("/personal-tasks", require("./personalTask.route"))
route.use("/assign", require("./assign.route"))
route.use("/access", require("./access.route"))
route.use("/reminders", require("./reminder.route"))
route.use("/strike", require("./strike.route"))
route.use("/manager-monthly-rankings", require("./managerMonthlyRanking.route"))
route.use("/power-star-monthly", require("./powerStarMonthly.route"))
route.use("/md-impex-access", require("./mdImpexAccess.route"))
route.use("/headline", require("./headline.route"))
route.use("/meetings", require("./meeting.route"))
route.use("/md-impex-strikes", require("./mdImpexStrike.route"))

module.exports = route;